### ISSUE TITLE
GUI Scale 

### ISSUE THREAD

**Issue by mrpwes** [FurkanGM/TradeGui#9]
are there any solution for this ? "Small Phone Problem"

![88197002_206766383848257_2297750375999995904_n](https://user-images.githubusercontent.com/31194909/75409267-2cfa9a00-5953-11ea-8846-c96f6195eaad.jpg)

![88133086_214097779733660_8130864865083392000_n](https://user-images.githubusercontent.com/31194909/75409268-2ec45d80-5953-11ea-925e-8aa0d11061d6.jpg)

**Comment by mrpwes** [comment]
also about trade distance ? atleast 5blocks away? to become more reality ? thank you for reply .....

**Comment by FurkanGM** [comment]
> are there any solution for this ? "Small Phone Problem"
> 
> ![88197002_206766383848257_2297750375999995904_n](https://user-images.githubusercontent.com/31194909/75409267-2cfa9a00-5953-11ea-8846-c96f6195eaad.jpg)
> 
> ![88133086_214097779733660_8130864865083392000_n](https://user-images.githubusercontent.com/31194909/75409268-2ec45d80-5953-11ea-925e-8aa0d11061d6.jpg)

Sorry, there is no solution for this.

> also about trade distance ? atleast 5blocks away? to become more reality ? thank you for reply .....

Yes i will add.
